# Generated by Django 3.2.19 on 2023-06-26 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_date']},
        ),
    ]
