# Generated by Django 3.2.19 on 2023-06-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
